### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe Kafka Test",
  "email": "kafka67899006@example.com",
  "address": "123 Main Street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
###